Pro_UILayer/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using Pro_UILayer.Areas.HelpPage.ModelDescriptions;
using Pro_UILayer.Areas.HelpPage.Models;

namespace Pro_UILayer.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

Pro_UILayer/Controllers/ProductController.cs
using Pro_EntityLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;

namespace Pro_UILayer.Controllers
{
    public class ProductController : Controller
    {
        HttpClient AppClient;

        public ProductController()
        {
            AppClient = new HttpClient();
            AppClient.BaseAddress = new Uri("http://localhost:50628/");
        }
        // GET: Product
        public ActionResult ShowProduct()
        {
            List<ProductModel> ProductList;
            if (Session["UserSession"] != null)
            {

                try
                {
                    //Client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", jwt.Value);
                  
                    AppClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", Session["UserSession"].ToString());
                    
                    var res = AppClient.GetAsync("ShowProducts").Result;

                    if (res.IsSuccessStatusCode)
                    {
                        var dat = res.Content.ReadAsAsync<List<ProductModel>>().Result;
                        ProductList = dat;
                        ViewBag.r = ProductList;

                        return View("Showproduct",ProductList);

                    }
                    else if (res.StatusCode == System.Net.HttpStatusCode.Unauthorized)
                    {
                        TempData["Err"] = "UnAthorized to access resource";
                        return RedirectToAction("login", "account");
                    }
                }
                catch (Exception ex)
                {
                    TempData["Err"] = ex.Message;
                }
            }
            else
            {
                return RedirectToAction("Login","Account");
            }
            return View();
        }

        public ActionResult AddProduct()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddProduct(ProductModel NewProduct)
        {           
            if (Session["UserSession"] != null)
            {

                try
                {
                    //Client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", jwt.Value);

                    AppClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", Session["UserSession"].ToString());

                    var res = AppClient.PostAsJsonAsync<ProductModel>("Addproduct", NewProduct).Result;

                    if (res.IsSuccessStatusCode)
                    {
                        return RedirectToAction("showproduct");

                    }
                    else if (res.StatusCode == System.Net.HttpStatusCode.Unauthorized)
                    {
                        TempData["Err"] = "UnAthorized to access resource";
                        return RedirectToAction("login", "account");
                    }
                }
                catch (Exception ex)
                {
                    TempData["Err"] = ex.Message;
                }
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
            return View();
        }
    }
}

Pro_UILayer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />

    <link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("ShowProducts", "ShowProduct", "Product", new { area = "" }, null)</li>

                    <li>@Html.ActionLink("Car", "ShowCars", "CarUi", new { area = "" }, null)</li>
                    @if (TempData["login"] != null)
                    {
                        if (TempData["login"].ToString() == "enabled")
                        {
                            <li>@Html.ActionLink("LogIn", "Login", "Account", new { area = "" }, null)</li>
                        }
                        else
                        {
                            <li>@Html.ActionLink("LogOut", "LogOut", "Account", new { area = "" }, null)</li>
                        }
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>